--- LIST OF RECORDS FOR MONITORING DATA (ONLY FOR CBBA)

CREATE TABLE fuel_monitoring (
    id_monitoring SERIAL PRIMARY KEY,
    monitoring_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);